package com.mcherm.versionedserialization.schemadiff.schema;

import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * An instance of this class contains the information from a JSON Schema. Is only
 * designed to work on JSON Schema generated by Victools with our particular settings,
 * NOT on an arbitrary JSON Schema. Probably has a bunch of other limitations too,
 * which we will eventually document. For instance, it only works on things that
 * serialize to a JSON object (not on things that serialize to a JSON string or
 * number).
 *
 * <p>This is an immutable value object.
 */
public class SchemaInfo {
    private final String schemaVersion;
    private final Map<String,Subschema> defs;
    private final Properties properties;

    /** Constructor */
    public SchemaInfo(final String schemaVersion, final Map<String,Subschema> defs, final Properties properties) {
        this.schemaVersion = schemaVersion;
        this.defs = defs;
        this.properties = properties;
    }

    public String getSchemaVersion() {
        return schemaVersion;
    }

    public Map<String,Subschema> getDefs() {
        return defs;
    }

    public Properties getProperties() {
        return properties;
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof SchemaInfo that)) return false;
        return Objects.equals(schemaVersion, that.schemaVersion) && Objects.equals(defs, that.defs) && Objects.equals(properties, that.properties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(schemaVersion, defs, properties);
    }

    @Override
    public String toString() {
        return "{\"$schema\":\"" + schemaVersion +
                "\",\"$defs\":{" +
                defs.entrySet().stream().map(e -> "\"" +e.getKey() + "\":" + e.getValue()).collect(Collectors.joining(",")) +
                "},\"type\":\"object\",\"properties\":" +
                properties.toString()
                + "}";
    }
}
